{% set name = "watermark" %}
{% set version = "2.0.1" %}
{% set sha256 = "07dd3ff5e07db1610d337ac45a168c4669ee9858a2b4e1bc744556d96d5d0f20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - ipython

  run:
    - python
    - ipython
    - certifi

test:
  imports:
    - watermark
    - certifi

about:
  home: https://github.com/rasbt/watermark
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'IPython magic function to print date/time stamps and various system information.'
  dev_url: https://github.com/rasbt/watermark

extra:
  recipe-maintainers:
    - proinsias
